jmeter:
    build: .
    labels:
        org.kurron.description: "Apache JMeter"
        org.kurron.version: "2.13"
    container_name: "jmeter"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
